# Generated by Django 3.2.15 on 2022-09-17 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('adresse', models.CharField(max_length=200)),
                ('numero_de_telephone', models.PositiveIntegerField()),
                ('observations', models.TextField()),
                ('genre', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10)),
                ('prescriptions', models.CharField(max_length=200)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
